### ISSUE TITLE
Feature Request: treeview in movie list

### ISSUE THREAD

**Issue by sapeish** [DanCooper/Ember-MM-Newscraper#77]
Since it is very common to use folders to classify everything, It would be nice to see the the movies in a folder treeview like this sample:
![image](https://f.cloud.github.com/assets/1246341/2301675/17780802-a153-11e3-9b35-184f5b1ad590.png)

**Comment by DanCooper** [comment]
http://bugs.embermediamanager.org/thebuggenie/embermediamanager
