### ISSUE TITLE
Feature Request: add/view Director name in movie name

### ISSUE THREAD

**Issue by sapeish** [DanCooper/Ember-MM-Newscraper#78]
It would be really usefull to be able to see the movie director name in the movie list, right now the only extra info that is possible to see the movie list is the year:

![image](https://f.cloud.github.com/assets/1246341/2301705/48bd2ebe-a154-11e3-8739-ff7bf0c8015e.png)

**Comment by DanCooper** [comment]
http://bugs.embermediamanager.org/thebuggenie/embermediamanager
